# Generated by Django 5.2 on 2025-05-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systempermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
