# Generated by Django 5.2 on 2025-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systempermission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systempermission',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='users.systempermission'),
        ),
    ]
