# Generated by Django 5.2 on 2025-05-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_systempermission_role_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempermission',
            name='actions',
            field=models.TextField(default=''),
        ),
    ]
