# Generated by Django 5.2 on 2025-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_systempermission_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempermission',
            name='module',
            field=models.CharField(choices=[('usuario', 'Usuarios')], default='usuario', max_length=50),
        ),
    ]
