# Generated by Django 5.2 on 2025-05-27 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_remove_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('compra_proveedor', 'Compra a proveedor'), ('devolucion', 'Devolución de cliente'), ('nuevo_ingreso', 'Nuevo ingreso'), ('venta', 'Venta'), ('producto_dañado', 'Producto dañado'), ('robo', 'Robo'), ('retiro', 'Retiro de inventario')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
